export const PRESET_CROPS = [
  {
    name: "Rice", season: "Kharif", growth_duration_days: 120,
    water_requirement: "High (1200-1800mm)", expected_yield_per_ha: 4.5,
    soil_ph_min: 5.5, soil_ph_max: 7.0, nitrogen_requirement: "High",
    notes: "Requires flooded conditions. Best in clay/loamy soil.",
    color: "#44aa22", icon: "🌾",
  },
  {
    name: "Wheat", season: "Rabi", growth_duration_days: 110,
    water_requirement: "Medium (450-650mm)", expected_yield_per_ha: 3.5,
    soil_ph_min: 6.0, soil_ph_max: 7.5, nitrogen_requirement: "High",
    notes: "Cool climate crop. Well-drained loamy soil preferred.",
    color: "#ddcc22", icon: "🌿",
  },
  {
    name: "Maize", season: "Kharif", growth_duration_days: 90,
    water_requirement: "Medium (500-800mm)", expected_yield_per_ha: 5.0,
    soil_ph_min: 5.8, soil_ph_max: 7.0, nitrogen_requirement: "Very High",
    notes: "Warm season crop. Sandy loam to loamy soil.",
    color: "#ffaa00", icon: "🌽",
  },
  {
    name: "Cotton", season: "Kharif", growth_duration_days: 180,
    water_requirement: "Medium (700-1200mm)", expected_yield_per_ha: 2.0,
    soil_ph_min: 5.8, soil_ph_max: 8.0, nitrogen_requirement: "High",
    notes: "Black cotton soil ideal. Long growing season.",
    color: "#ffffff", icon: "☁️",
  },
  {
    name: "Sugarcane", season: "Annual", growth_duration_days: 365,
    water_requirement: "Very High (1500-2500mm)", expected_yield_per_ha: 70.0,
    soil_ph_min: 6.0, soil_ph_max: 7.5, nitrogen_requirement: "Very High",
    notes: "Tropical crop. Deep fertile loamy soil.",
    color: "#88dd44", icon: "🎋",
  },
  {
    name: "Soybean", season: "Kharif", growth_duration_days: 100,
    water_requirement: "Medium (450-700mm)", expected_yield_per_ha: 2.5,
    soil_ph_min: 6.0, soil_ph_max: 7.0, nitrogen_requirement: "Low (fixes N)",
    notes: "Nitrogen fixing legume. Well-drained loamy soil.",
    color: "#aacc44", icon: "🫘",
  },
  {
    name: "Groundnut", season: "Kharif", growth_duration_days: 110,
    water_requirement: "Low (500-600mm)", expected_yield_per_ha: 2.0,
    soil_ph_min: 6.0, soil_ph_max: 7.0, nitrogen_requirement: "Low",
    notes: "Sandy loam soil. Good drainage essential.",
    color: "#cc9944", icon: "🥜",
  },
  {
    name: "Tomato", season: "Rabi/Summer", growth_duration_days: 75,
    water_requirement: "Medium (400-600mm)", expected_yield_per_ha: 25.0,
    soil_ph_min: 6.0, soil_ph_max: 7.0, nitrogen_requirement: "High",
    notes: "Well-drained sandy loam. Warm days, cool nights.",
    color: "#dd4422", icon: "🍅",
  },
  {
    name: "Onion", season: "Rabi", growth_duration_days: 120,
    water_requirement: "Low (350-550mm)", expected_yield_per_ha: 20.0,
    soil_ph_min: 6.0, soil_ph_max: 7.5, nitrogen_requirement: "Medium",
    notes: "Well-drained fertile loamy soil preferred.",
    color: "#cc6688", icon: "🧅",
  },
  {
    name: "Turmeric", season: "Kharif", growth_duration_days: 270,
    water_requirement: "High (1500mm)", expected_yield_per_ha: 20.0,
    soil_ph_min: 4.5, soil_ph_max: 7.5, nitrogen_requirement: "Medium",
    notes: "Loamy to clay loam. Partial shade tolerated.",
    color: "#ffaa00", icon: "🌿",
  },
  {
    name: "Chilli", season: "Kharif/Rabi", growth_duration_days: 150,
    water_requirement: "Medium (600-1250mm)", expected_yield_per_ha: 3.0,
    soil_ph_min: 6.0, soil_ph_max: 7.0, nitrogen_requirement: "High",
    notes: "Well-drained sandy loam. Sensitive to waterlogging.",
    color: "#dd2200", icon: "🌶️",
  },
  {
    name: "Sunflower", season: "Kharif/Rabi", growth_duration_days: 90,
    water_requirement: "Low (500-750mm)", expected_yield_per_ha: 1.5,
    soil_ph_min: 6.0, soil_ph_max: 7.5, nitrogen_requirement: "Medium",
    notes: "Drought tolerant. Well-drained loamy soil.",
    color: "#ffdd00", icon: "🌻",
  },
  {
    name: "Banana", season: "Annual", growth_duration_days: 300,
    water_requirement: "High (1200-2200mm)", expected_yield_per_ha: 40.0,
    soil_ph_min: 6.0, soil_ph_max: 7.5, nitrogen_requirement: "Very High",
    notes: "Rich loamy well-drained soil. Frost sensitive.",
    color: "#ffee44", icon: "🍌",
  },
  {
    name: "Mango", season: "Annual", growth_duration_days: 120,
    water_requirement: "Low (250-500mm)", expected_yield_per_ha: 10.0,
    soil_ph_min: 5.5, soil_ph_max: 7.5, nitrogen_requirement: "Medium",
    notes: "Deep well-drained alluvial soil. Dry flowering season.",
    color: "#ffaa22", icon: "🥭",
  },
  {
    name: "Jowar", season: "Kharif", growth_duration_days: 100,
    water_requirement: "Low (400-600mm)", expected_yield_per_ha: 2.0,
    soil_ph_min: 6.0, soil_ph_max: 8.5, nitrogen_requirement: "Medium",
    notes: "Drought resistant. Black cotton or loamy soil.",
    color: "#cc9933", icon: "🌾",
  },
]

export const SEASONS = ["Kharif", "Rabi", "Summer", "Annual", "Kharif/Rabi", "Rabi/Summer"]